### ISSUE TITLE
LatLng Debug and Display print different values (rad / deg)

### ISSUE THREAD

**Issue by evavh** [HydroniumLabs/h3o#10]
When debugging my code today, it was quite confusing to me that the `Debug` implementation for `LatLng` printed the latitude and longitude in radians, while I had initialized them in degrees. I checked the documentation, and found out that the `Display` implementation _does_ print degrees. `Debug` is automatically derived, and so it uses the struct's own variables in radians.

I think this could be solved by writing a manual `Debug` implementation, and adding the units to the output of both `Debug` and `Display`. It would also save some confusion if the unit was consistent between them, though maybe `Debug` could print both units.

What do you think?

**Comment by grim7reaper** [comment]
That's a good point.

Originally, both `Display` and `Debug` printed radians, but then I moved to degrees for `Display` (since this is what most users are gonna use I believe), which left the auto-generated `Debug` impl with radians and created this confusing situation.

While I would like to keep radians for `Debug` (since algorithms are using radians internally, that's good for troubleshooting), I could:
- document, in the type's top level doc, what each impl are priting (printing the unit for each value is gonna be noisy when you have a lot of values, e.g. a `Vec`).
- impl `Debug` to print both radians and degrees

I think this would solve this issue and avoid the confusion.

**Comment by evavh** [comment]
That sounds like a good solution!
