### ISSUE TITLE
Question: leverage gpu or simd support 

### ISSUE THREAD

**Issue by LegNeato** [HydroniumLabs/h3o#16]
Hello! Random question: do you see any opportunities for moving h3 calcs on to the GPU or simd? I'm not really sure if the h3 representation or processing are conducive to this, but at a high level it seems calcs like K-Ring and parent child relationships could be highly parallellized? Or is everything already in lookup tables?

**Comment by grim7reaper** [comment]
H3 (and h3o) already uses a handful of lookup table yeah.

For SIMD, probably.

In fact I already use a similar technique, [SWAR](https://en.wikipedia.org/wiki/SWAR), when applicable: for example, you can compare the H3 version of `isValidCell` that [loop over every children](https://github.com/uber/h3/blob/54f46c4e86060e76925988a0d167cd84a7f72ce0/src/h3lib/lib/h3Index.c#L124-L127) vs [my version](https://github.com/HydroniumLabs/h3o/blob/e2208275e1bc5f42322cf53887af3985c1d5ad16/src/index/cell.rs#L1848-L1856) that validate all of them in parallel (the magic happens inside inside `has_unused_direction`)

Now, for real SIMD (processing 128, 256 or 512 bytes at once) it may be applicable but only if:
- you process a bunch a cells at once
- the code is "simple" (i.e. you may be able to SIMD the `isValidCell`, but not the `cellToLatLng` because I think transcendental functions are a SIMD-killer).

Note that you can also get some perf boost with good 'ol parallelism (using rayon), for instance `uncompactCells` is embarrassingly parallelizable if you have enough works to do (i.e. many cells to uncompact and/or the gap between parent/children resolution is big enough).

On GPU programming I don't know enougb about it to tell if it's applicable here, and if so where.
