### ISSUE TITLE
Certain polygons hit `debug_assert`

### ISSUE THREAD

**Issue by grovesNL** [HydroniumLabs/h3o#23]
Hi! :wave: Thank you for this crate. I've been testing it out with some different shapes and it's working great so far!

There's an area in my application where people can provide their own polygon coordinates, so I was testing out some different inputs to make sure we handle unexpected inputs well, especially when covering a large amount of cells.

For one set of inputs, I noticed that if I write a test like this:
```rust
#[test]
fn debug_assert_issue() {
    let poly: geo::Polygon<f64> = polygon![
        (x: 0.0, y: 5.0),
        (x: 5.0, y: 5.0),
        (x: 5.0, y: 0.0),
        (x: -179.0, y: -90.0),
    ];
    let shape = Polygon::from_degrees(poly).unwrap();
    println!("{:#?}", shape);
    let config = PolyfillConfig::new(Resolution::Six)
        .containment_mode(ContainmentMode::Covers);
    let _ = shape.to_cells(config).collect::<Vec<_>>();
}
```
this results in
```
Polygon {
    exterior: Ring {
        geom: Polygon {
            exterior: LineString(
                [
                    Coord {
                        x: 0.0,
                        y: 0.08726646259971647,
                    },
                    Coord {
                        x: 0.08726646259971647,
                        y: 0.08726646259971647,
                    },
                    Coord {
                        x: 0.08726646259971647,
                        y: 0.0,
                    },
                    Coord {
                        x: 3.159045946109736,
                        y: -1.5707963267948966,
                    },
                    Coord {
                        x: 0.0,
                        y: 0.08726646259971647,
                    },
                ],
            ),
            interiors: [],
        },
        bbox: Rect {
            min: Coord {
                x: 0.0,
                y: -1.5707963267948966,
            },
            max: Coord {
                x: 3.159045946109736,
                y: 0.08726646259971647,
            },
        },
        is_transmeridian: true,
    },
    interiors: [],
}
thread 'api::geom::to_cells::debug_assert_issue' panicked at src\geom\geometry\polygon.rs:335:17:
cell index 867570d57ffffff in polygon
```

which points to the `debug_assert` at https://github.com/HydroniumLabs/h3o/blob/6dbf5023e9df2a84f04233dedae0ec7654303438/src/geom/geometry/polygon.rs#L335-L338

It's possible I should be detecting rings like this on the caller-side, but I'm not sure exactly which conditions trigger this. I'm guessing it's not supposed to fail here, but if so it would be nice to fail with an error.

**Comment by grim7reaper** [comment]
Hi,

Thanks for the report and test case 🙏 

I think we're hitting [a known limitation of the original H3 polyfill algorithm](https://github.com/uber/h3-js/issues/24#issuecomment-431893796), namely it cannot handle/misinterpret polygon segments of greater than 180 degrees longitude and your shape seems to contains such segment:

```
[src/geom/geometry/ring.rs:166] (line.start.x - line.end.x).abs() = 5.0
[src/geom/geometry/ring.rs:166] (line.start.x - line.end.x).abs() = 0.0
[src/geom/geometry/ring.rs:166] (line.start.x - line.end.x).abs() = 184.0
```

For the record, the code to detect the antimeridiant crossing looks like that:

```
     ring.lines()
        .any(|line| (line.start.x - line.end.x).abs() > arc_threshold)
```

Dunno if I can find another way more robust than that, to avoid this pitfall 🤔 
I will think about it, but suggestions are welcome 🙂 

Meanwhile, the simpler solution would be to split such shape in two.

**Comment by grovesNL** [comment]
Sounds good! I didn't realize H3 had this limitation. I can easily split the polygon in this case.

To avoid getting caught on the `debug_assert` accidentally while running test cases, it would be great if could document it as part of the polyfill and return something like `Err(LineTooLong)` whenever a segment exceeds `arc_threshold`.

It would also be useful if the arc threshold was exposed in degrees and radians so I could reference it in my code (e.g., when picking the polygon split point), although in practice this doesn't matter much if it's always going to be 180/pi.

**Comment by grim7reaper** [comment]
Yeah at the very least I'll document this limitation (as well as [the pole one](https://github.com/uber/h3-py/issues/285#issuecomment-1252831834))

Can't really return an error on segment exceeding `arc_threshold` though, as we treat this as a signal that we're crossing the antimeridian and act accordingly.
The issue is when this heuristic fail (like in your case) and we wrongly interpret it.

I'll spend some time to see if I can come up with something more robust 🙂  (and if not, at least it'll be properly documented)

As for the `arc_threshold`, yeah it's always 180/π.

**Comment by grovesNL** [comment]
Oh ok that makes sense. Alternatively just returning an `Err` instead of the existing `debug_assert` would be useful. I assume the polyfill becomes unstable at that point anyway, but callers could treat the `Err` as signal that the input might be problematic and try to deal with it in some way.

This is probably a naive question, but what's the reason h3 can't test whether a line segment crosses an antimeridian directly (e.g., the start and end are on different sides of an antimeridian) instead of the arc threshold heuristic?

**Comment by grim7reaper** [comment]
> lternatively just returning an Err instead of the existing debug_assert would be useful. 

Agreed, the problem is that this assert is costly (it does a Point-in-Polygon check), that's why it's only enabled in debug mode.

If I enable this in release in order to return an error, it would destroy the performance (10x to 100x slowdown).

In fact, the huge performance boost I got last year (see c85aa2c5eaeb95a073938671523868edb7339dbd), which put me well ahead of the official H3 implementation, was mainly due to a huge reduction of the number of PIP check.

> This is probably a naive question, but what's the reason h3 can't test whether a line segment crosses an antimeridian directly (e.g., the start and end are on different sides of an antimeridian) instead of the arc threshold heuristic?

That's a good question.

Either it's an oversight or, more likely, there are some cases not covered by this simple test.

That's something I'll consider and test while searching for a better predicate/detection.

**Comment by grim7reaper** [comment]
Yeah there is no easy but I'll try to find one nonetheless, as it's not really a good things to enter an infinite loop or silently return wrong data.

Plus, there may be a real bug here, as the computed outline (blue) is wrong, even considering the "shifted" shape (red).
Your shape (the original one) is in green.

<img width="960" alt="Screenshot 2024-02-26 at 21 17 19" src="https://github.com/HydroniumLabs/h3o/assets/6479907/f421607f-f708-4d68-93cc-3bdb8f5500ba">

So I'll do a little more digging on this.

**Comment by grim7reaper** [comment]
Ok, some progress.
I may have a way to detect when the "antimeridian crossing" heuristic is too eagerly applied: in this case we usually end up with self-intersecting "corrected" shape!
It's not 100% reliable but seems to work in several case (including your shape).

That being said, the original shape still can't be polyfilled, probably because we got the outline wrong. Still need to get to the bottom of this.

**Comment by grim7reaper** [comment]
So, from the few tests I've done it's seems like the issue stems from the outline computation whose approximation really goes south on this shape (either because we have a very long segment and/or because it goes up to the pole).

Haven't checked if H3 have the same issue, I would say yes since the outline approximation is the same, but they may get back on their feet later since they do a costly PIP check for every single cell (and that's why they are so slow).

I do have an alternative approach to try that may solve the issue 🙂, just need some bandwidth to give it a try (should happen soon 🤞).

**Comment by grim7reaper** [comment]
Finally had some time to get back to this, thanks for your patience. :)

As it happens, it seems that fixing the heuristic was enough.
I'm gonna publish a new version with the fix.

**Comment by grovesNL** [comment]
@grim7reaper awesome, thank you!
