### ISSUE TITLE
conversion to web or wkt

### ISSUE THREAD

**Issue by yiftachn** [HydroniumLabs/h3o#29]
I think some usage examples would help greatly for rust new comers, FYI.
Thanks for this amazing library

**Comment by grim7reaper** [comment]
Yeah, I'm open to adding more examples if it can help 🙂 
Which kind do you think are missing?

For the conversion to WKT (or other formats really), the stance of `h3o` is to [provide a function to convert a polygon into a Rust geometry](https://docs.rs/h3o/latest/h3o/geom/trait.ToGeo.html#tymethod.to_geom) (from the `geo` crate) and then you can leverage the georust ecosystem to convert to [WKT](https://docs.rs/wkt/0.10.3/wkt/#write-geo_types-to-a-wkt-string), [KML](https://docs.rs/kml/latest/kml/#conversion), ...

This avoid bloating the library with the support of too many format: you get a geometry and then you can use other crate to convert in what you need.

There is a built-in support for [GeoJSON](https://docs.rs/h3o/latest/h3o/geom/trait.ToGeo.html#method.to_geojson) in the library though, mainly because I've used it a lot for debugging during the development.
